name: Android Release APK (signed from ZIP)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Unzip project
        shell: bash
        run: |
          ZIPFILE="$(ls *.zip | head -n 1)"
          echo "Using ZIP: $ZIPFILE"
          mkdir buildsrc
          unzip -q "$ZIPFILE" -d buildsrc
          ls -la buildsrc

      - name: Assemble Release (unsigned)
        shell: bash
        working-directory: buildsrc/GyroRush
        run: gradle assembleRelease

      - name: Restore keystore from secrets
        shell: bash
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
          ls -l keystore.jks

      - name: Find unsigned release APK
        id: findapk
        shell: bash
        run: |
          APK=$(ls buildsrc/GyroRush/app/build/outputs/apk/release/*-unsigned.apk | head -n 1)
          if [ -z "$APK" ]; then
            echo "No unsigned APK found"; exit 1
          fi
          echo "apk=$APK" >> $GITHUB_OUTPUT

      - name: Zipalign
        shell: bash
        run: |
          ALIGNED=app-release-aligned.apk
          zipalign -f -v 4 "${{ steps.findapk.outputs.apk }}" "$ALIGNED"
          echo "ALIGNED=$ALIGNED" >> $GITHUB_ENV

      - name: Sign with apksigner
        shell: bash
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
        run: |
          apksigner sign \
            --ks keystore.jks \
            --ks-key-alias "$KEY_ALIAS" \
            --ks-pass pass:"$KEYSTORE_PASS" \
            --key-pass pass:"$KEY_PASS" \
            "$ALIGNED"
          apksigner verify "$ALIGNED"

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: GyroRush-release-apk
          path: app-release-aligned.apk
